name: source_github

config-version: 2

version: 0.1.0

profile: airbyte

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  source_github:
    materialized: view
    staging:
      materialized: view

vars:
  database: airbyte_dbt_default
  schema: airbyte_schema_default
  using_fivetran: False
