name: source_zendesk_support

config-version: 2

version: 0.1.0

profile: airbyte

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - '>=1.0.0'
  - <2.0.0

models:
  source_zendesk_support:
    materialized: table
    staging:
      materialized: view

vars:
  database: postgres
  schema: source_zendesk_support
