name: source_zendesk_support

config-version: 2

version: 0.1.0

profile: airbyte

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_zendesk_support:
    materialized: view
    +schema: dbt_zendesk_support
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  airbyte_database: airbyte_dbt_default
  airbyte_schema: airbyte_schema_default
  using_fivetran: False
