name: integration_test_google_ads

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - '>=1.0.0'
  - <2.0.0

models:
  airbyte_dbt_source_google_ads:
    materialized: view
    +schema: dbt_source_google_ads
    fivetran_converter:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_source_google_ads"

  # Required by Fivetran dbt model
  google_ads_database: "airbyte_db_default"
  google_ads_schema: "dbt_source_google_ads"

  google_ads__account_history_identifier: "account_history"
  google_ads__account_stats_identifier: "account_stats"
  google_ads__ad_history_identifier: "ad_history"
  google_ads__ad_stats_identifier: "ad_stats"
  google_ads__campaign_history_identifier: "campaign_history"
  google_ads__campaign_stats_identifier: "campaign_stats"
  google_ads_ad_group_criterion_history_identifier: "group_criterion_history"
  google_ads__ad_group_history_identifier: "group_history"
  google_ads__ad_group_stats_identifier: "group_stats"
  google_ads__keyword_stats_identifier: "keyword_stats"
