version: 2

sources:
  - name: source_salesforce
    schema: "{{ var('airbyte_schema', target.schema) }}"
    database: "{{ var('airbyte_database', target.database) }}"
    loader: airbyte
    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: ChatterExtensionConfig
        columns:
          - name: Id
            description: ""
            data_type: string
          - name: IsDeleted
            description: ""
            data_type: boolean
          - name: CreatedDate
            description: ""
            data_type: string
          - name: CreatedById
            description: ""
            data_type: string
          - name: LastModifiedDate
            description: ""
            data_type: string
          - name: LastModifiedById
            description: ""
            data_type: string
          - name: SystemModstamp
            description: ""
            data_type: string
          - name: ChatterExtensionId
            description: ""
            data_type: string
          - name: CanCreate
            description: ""
            data_type: boolean
          - name: CanRead
            description: ""
            data_type: boolean
          - name: Position
            description: ""
            data_type: integer
