version: 2

sources:
  - name: source_salesforce
    schema: "{{ var('airbyte_schema', target.schema) }}"
    database: "{{ var('airbyte_database', target.database) }}"
    loader: airbyte
    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: ConnectedApplication
        columns:
          - name: Id
            description: ""
            data_type: string
          - name: Name
            description: ""
            data_type: string
