version: 2

sources:
  - name: source_salesforce
    schema: "{{ var('airbyte_schema', target.schema) }}"
    database: "{{ var('airbyte_database', target.database) }}"
    loader: airbyte
    loaded_at_field: _airbyte_extracted_at
    tables:
      - name: FiscalYearSettings
        columns:
          - name: Id
            description: ""
            data_type: string
          - name: PeriodId
            description: ""
            data_type: string
          - name: StartDate
            description: ""
            data_type: string
          - name: EndDate
            description: ""
            data_type: string
          - name: Name
            description: ""
            data_type: string
          - name: IsStandardYear
            description: ""
            data_type: boolean
          - name: YearType
            description: ""
            data_type: string
          - name: QuarterLabelScheme
            description: ""
            data_type: string
          - name: PeriodLabelScheme
            description: ""
            data_type: string
          - name: WeekLabelScheme
            description: ""
            data_type: string
          - name: QuarterPrefix
            description: ""
            data_type: string
          - name: PeriodPrefix
            description: ""
            data_type: string
          - name: WeekStartDay
            description: ""
            data_type: integer
          - name: Description
            description: ""
            data_type: string
          - name: SystemModstamp
            description: ""
            data_type: string
