WITH tmp AS (
    SELECT
        "$insert_id" AS _insert_id,
        "$schema" AS "schema",
        adid AS ad_id,
        amplitude_id,
        app,
        city,
        client_event_time,
        client_upload_time,
        country,
        "data",
        device_brand,
        device_carrier,
        device_family,
        device_id,
        device_manufacturer,
        device_model,
        device_type,
        dma,
        event_id AS id,
        event_properties,
        event_time,
        event_type,
        group_properties,
        groups AS group_types,
        idfa,
        ip_address,
        is_attribution_event,
        "language",
        library,
        location_lat,
        location_lng,
        os_name,
        os_version,
        paying,
        platform,
        processed_time,
        region,
        server_received_time,
        server_upload_time,
        session_id,
        start_version,
        user_creation_time,
        user_id,
        user_properties,
        uuid,
        version_name
    FROM
        {{ source('source_amplitude', 'events') }}
    )
SELECT * FROM tmp
