name: integration_test_snapchat_marketing

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_snapchat_marketing:
    materialized: view
    +schema: dbt_source_snapchat_marketing
    fivetran_converter:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_source_snapchat_marketing"

  # Required by Fivetran dbt model
  snapchat_marketing_database: "airbyte_db_default"
  snapchat_marketing_schema: "dbt_source_snapchat_marketing"

  snapchat_ads_ad_account_history_identifier: "ad_account_history"
  snapchat_ads_ad_history_identifier: "ad_history"
  snapchat_ads_ad_hourly_report_identifier: "ad_hourly_report"
  snapchat_ads_ad_squad_history_identifier: "ad_squad_history"
  snapchat_ads_ad_squad_hourly_report_identifier: "ad_squad_hourly_report"
  snapchat_ads_campaign_history_identifier: "campaign_history"
  snapchat_ads_campaign_hourly_report_identifier: "campaign_hourly_report"
  snapchat_ads_creative_history_identifier: "creative_history"
