name: source_facebook_marketing

config-version: 2

version: 0.1.0

profile: airbyte

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - '>=1.0.0'
  - <2.0.0

models:
  source_facebook_marketing:
    +materialized: view
    +schema: staging
  facebook_ads_source:
    +materialized: view
    +schema: staging
    tmp:
      +enabled: false
  facebook_ads:
    +schema: reporting
    intermediate:
      +materialized: ephemeral

vars:
  airbyte_database: postgres
  airbyte_schema: dbt_source_facebook_marketing

  facebook_ads_database: postgres
  facebook_ads_schema: dbt_source_facebook_marketing

  # airbyte:
  # facebook_ads:
  #   sources:
  #     ad_accounts:
  #       - name: facebook_ads_us
  #         table: ad_account
  #     ads:
  #       - name: facebook_ads_us
  #         table: ads
  #     ad_sets:
  #       - name: facebook_ads_us
  #         table: ad_sets
  #     ads_insights:
  #       - name: facebook_ads_us
  #         table: ads_insights
  #     campaigns:
  #       - name: facebook_ads_us
  #         table: campaigns
  #     ad_creatives:
  #       - name: facebook_ads_us
  #         table: ad_creatives
  # basic_ad_passthrough_metrics:
  #   - name: video_play_actions
  #   - name: video_p95_watched_actions

  # facebook_ads__basic_ad_passthrough_metrics:
  #   - name: video_play_actions
  #   - name: video_p95_watched_actions
