name: source_linkedin_ads

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  source_linkedin_ads:
    materialized: view
    fivetran_converter:
      materialized: view

vars:
  airbyte_database: airbyte_default_database
  airbyte_schema: airbyte_default_schema
  using_fivetran_model: True
  linkedin_ads_database: airbyte_default_database
  linkedin_ads_schema: airbyte_dbt_source_linkedin_ads
