name: integration_test_amplitude

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_amplitude:
    materialized: view
    +schema: dbt_amplitude
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_amplitude"

  # Required by Fivetran dbt model
  amplitude_database: "airbyte_db_default"
  amplitude_schema: "airbyte_dbt_amplitude"

  using_event_type: False

  amplitude_event_identifier: "events"
