name: integration_test_recurly

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_recurly:
    materialized: view
    +schema: dbt_recurly
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_source_recurly"

  # Required by Fivetran dbt model
  recurly_database: "airbyte_db_default"
  recurly_schema: "airbyte_dbt_source_recurly"

  recurly__using_credit_payment_history: False
  recurly__using_subscription_add_on_history: False
  recurly__using_subscription_change_history: False

  account_coupon_redemption_identifier: "account_coupon_redemptions"
  account_note_identifier: "account_notes"
  account_identifier: "accounts"
  account_balance_identifier: "accounts"
  add_on_identifier: "add_ons"
  billing_info_identifier: "billing_info"
  coupon_redemption_identifier: "account_coupon_redemptions"
  coupon_identifier: "coupons"
  credit_payment_identifier: "credit_payments"
  export_date_identifier: "export_dates"
  invoice_history_identifier: "invoices"
  line_item_identifier: "line_items"
  measured_unit_identifier: "measured_units"
  plan_identifier: "plans"
  shipping_address_identifier: "shipping_addresses"
  shipping_method_identifier: "shipping_methods"
  subscription_identifier: "subscriptions"
  transaction_identifier: "transactions"
  unique_coupon_identifier: "unique_coupons"
