name: integration_test_recurly

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_recurly:
    materialized: view
    +schema: dbt_source_recurly
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_source_recurly"

  # Required by Fivetran dbt model
  recurly_database: "airbyte_db_default"
  recurly_schema: "airbyte_dbt_source_recurly"

  recurly__using_credit_payment_history: False
  recurly__using_subscription_add_on_history: False
  recurly__using_subscription_change_history: False

  recurly_account_balance_identifier: "accounts"
  recurly_account_identifier: "accounts"
  recurly_account_note_identifier: "account_notes"
  recurly_account_coupon_redemption_identifier: "account_coupon_redemptions"
  recurly_billing_info_identifier: "billing_info"
  recurly_coupon_redemption_identifier: "account_coupon_redemptions"
  recurly_coupon_identifier: "coupons"
  recurly_coupon_discount_identifier: "coupons"
  recurly_credit_payment_identifier: "credit_payments"
  recurly_invoice_history_identifier: "invoices"
  recurly_invoice_coupon_redemption_identifier: "invoices"
  recurly_invoice_subscription_history_identifier: "invoices"
  recurly_line_item_identifier: "line_items"
  recurly_plan_identifier: "plans"
  recurly_plan_currency_history_identifier: "plans"
  recurly_subscription_identifier: "subscriptions"
  recurly_subscription_change_identifier: "subscriptions"
  recurly_subscription_add_on_history_identifier: "subscriptions"
  recurly_transaction_identifier: "transactions"
  recurly_subscription_history_identifier: "transactions"
  recurly_transaction_subscription_identifier: "transactions"
