name: integration_test_recurly

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_recurly:
    materialized: view
    +schema: dbt_source_recurly
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_source_recurly"

  # Required by Fivetran dbt model
  recurly_database: "airbyte_db_default"
  recurly_schema: "airbyte_dbt_source_recurly"

  recurly__using_credit_payment_history: False
  recurly__using_subscription_add_on_history: False
  recurly__using_subscription_change_history: False

  account_balance_identifier: "accounts"
  account_identifier: "accounts"
  account_note_identifier: "account_notes"
  account_coupon_redemption_identifier: "account_coupon_redemptions"
  billing_info_identifier: "billing_infos"
  coupon_redemption_identifier: "account_coupon_redemptions"
  coupon_identifier: "coupons"
  coupon_discount_identifier: "coupons"
  credit_payment_identifier: "credit_payments"
  invoice_history_identifier: "invoices"
  invoice_coupon_redemption_identifier: "invoices"
  invoice_subscription_history_identifier: "invoices"
  line_item_identifier: "line_items"
  plan_identifier: "plans"
  plan_currency_history_identifier: "plans"
  subscription_identifier: "subscriptions"
  subscription_change_identifier: "subscriptions"
  subscription_add_on_history_identifier: "subscriptions"
  transaction_identifier: "transactions"
  subscription_history_identifier: "transactions"
  transaction_subscription_identifier: "transactions"
