version: 2

models:
  - name: automations
    schema: "{{ var('airbyte_schema', target.schema) }}"
    database: "{{ var('airbyte_database', target.database) }}"
    identifier: "{{ var('mailchimp_automations_identifier', 'automations') }}"
    description: All fields and field values associated with automations.
    config:
      +enabled: "{{ var('using_fivetran_model', False) }}"
    columns:
      - name: automation_id
        description: Identifier for the automation.
      - name: list_id
        description: Identifier for the list associated with the automation.
      - name: segment_id
        description: Identifier for the segment associated with the automation.
      - name: segment_text
        description: Text description of the segment associated with the automation.
      - name: started_timestamp
        description: Timestamp when the automation started.
      - name: created_timestamp
        description: Timestamp when the automation was created.
      - name: status
        description: Current status of the automation.
      - name: title
        description: Title of the automation.
      - name: trigger_settings
        description: Settings related to the automation triggers.
