name: integration_test_intercom

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_intercom:
    materialized: view
    +schema: dbt_source_intercom
    fivetran_converter:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "dbt_source_intercom"

  # Required by Fivetran dbt model
  intercom_database: "airbyte_db_default"
  intercom_schema: "dbt_source_intercom"
  admin: "admin"
  company_history: "company_history"
  company_tag_history: "company_tag_history"
  contact_company_history: "contact_company_history"
  contact_history: "contact_history"
  contact_tag_history: "contact_tag_history"
  conversation_contact_history: "conversation_contact_history"
  conversation_history: "conversation_history"
  conversation_part_history: "conversation_part_history"
  conversation_tag_history: "conversation_tag_history"
  tag: "tag"
  team_admin: "team_admin"
  team: "team"
#  intercom__using_contact_company: true
#  intercom__using_company_tags: true
#  intercom__using_contact_tags: true
#  intercom__using_conversation_tags: true
#  intercom__using_team: true
