name: integration_test_github

config-version: 2

version: 0.1.0

profile: integration_tests

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - ">=1.0.0"
  - <2.0.0

models:
  airbyte_dbt_source_github:
    materialized: view
    +schema: dbt_github
    staging:
      materialized: view
    tmp:
      materialized: view

vars:
  # Required by Airbyte dbt model
  using_fivetran_model: True
  airbyte_database: "airbyte_db_default"
  airbyte_schema: "airbyte_dbt_github"

  # Required by Github dbt model
  github_database: "airbyte_db_default"
  github_schema: "airbyte_dbt_github"

  using_repo_team: False
