name: source-zendesk-support_erd

config-version: 2

version: x.y.z

profile: airbyte

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_modules
  - logs

require-dbt-version:
  - '>=1.0.0'
  - <2.0.0

models:
  source-zendesk-support_erd:
    materialized: table
    staging:
      materialized: view
