name: Run Integration Tests for Dbt Models

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: checkout
        uses: actions/checkout@v2

      - name: Get what connector we are testing
        id: get_connector
        run: echo "::set-output name=connector::source_zendesk_support"

      - name: Access folder
        run: cd connectors/${{ steps.get_connector.outputs.connector }}

      - name: Install the project dependencies
        run: poetry install

      - name: Run pwd
        run: echo pwd
