name: Run Integration Tests for Dbt Models

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: checkout
        uses: actions/checkout@v2

      - name: Install the project dependencies
        run: poetry install

      - name: Ensure .dbt directory exists
        run: mkdir -p ~/.dbt

      - name: Copy profiles
        run: cp .github/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - name: Get what connector we are testing
        id: get_connector
        run: echo "::set-output name=connector::source_zendesk_support"

      - name: Run Integration Tests for Postgres
        working-directory: connectors/${{ steps.get_connector.outputs.connector }}/integration_test
        run: dbt run --target postgres
